-- MySQL Script generated by MySQL Workbench
-- Wed Oct 28 13:34:04 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Adresse` (
  `idAdresse` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rue` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdresse`),
  UNIQUE INDEX `idAdresse_UNIQUE` (`idAdresse` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Etudiant` (
  `idEtudiant` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Diplome` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `Adresse_idAdresse` INT NOT NULL,
  PRIMARY KEY (`idEtudiant`),
  UNIQUE INDEX `idEtudiant_UNIQUE` (`idEtudiant` ASC),
  INDEX `fk_Etudiant_Adresse_idx` (`Adresse_idAdresse` ASC),
  CONSTRAINT `fk_Etudiant_Adresse`
    FOREIGN KEY (`Adresse_idAdresse`)
    REFERENCES `mydb`.`Adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT;


-- -----------------------------------------------------
-- Table `mydb`.`Professeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professeur` (
  `idProfesseur` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `competence` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProfesseur`),
  UNIQUE INDEX `idProfesseur_UNIQUE` (`idProfesseur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Salle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Salle` (
  `idSalle` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSalle`),
  UNIQUE INDEX `idSalle_UNIQUE` (`idSalle` ASC),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cours` (
  `idCours` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `heureDebut` DATETIME NOT NULL,
  `heureFin` DATETIME NOT NULL,
  `Professeur_idProfesseur` INT NOT NULL,
  `Salle_idSalle` INT NOT NULL,
  PRIMARY KEY (`idCours`),
  UNIQUE INDEX `idCours_UNIQUE` (`idCours` ASC),
  INDEX `fk_Cours_Professeur1_idx` (`Professeur_idProfesseur` ASC),
  INDEX `fk_Cours_Salle1_idx` (`Salle_idSalle` ASC),
  CONSTRAINT `fk_Cours_Professeur1`
    FOREIGN KEY (`Professeur_idProfesseur`)
    REFERENCES `mydb`.`Professeur` (`idProfesseur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cours_Salle1`
    FOREIGN KEY (`Salle_idSalle`)
    REFERENCES `mydb`.`Salle` (`idSalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Participant` (
  `idParticipant` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `place` VARCHAR(45) NOT NULL,
  `Cours_idCours` INT NOT NULL,
  `Etudiant_idEtudiant` INT NOT NULL,
  PRIMARY KEY (`idParticipant`),
  UNIQUE INDEX `idParticipant_UNIQUE` (`idParticipant` ASC),
  INDEX `fk_Participant_Cours1_idx` (`Cours_idCours` ASC),
  INDEX `fk_Participant_Etudiant1_idx` (`Etudiant_idEtudiant` ASC),
  CONSTRAINT `fk_Participant_Cours1`
    FOREIGN KEY (`Cours_idCours`)
    REFERENCES `mydb`.`Cours` (`idCours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participant_Etudiant1`
    FOREIGN KEY (`Etudiant_idEtudiant`)
    REFERENCES `mydb`.`Etudiant` (`idEtudiant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
